# Generated by Django 3.2.9 on 2022-03-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('item_id', models.IntegerField(db_column='id', primary_key=True, serialize=False, verbose_name='id')),
                ('item_name', models.CharField(db_column='name', max_length=100, verbose_name='name')),
                ('item_quantity', models.IntegerField(db_column='quantity', default=0, verbose_name='quantity')),
                ('item_brief', models.TextField(db_column='brief', null=True, verbose_name='brief')),
                ('item_price', models.DecimalField(db_column='price', decimal_places=2, default=0.0, max_digits=8, verbose_name='_price')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
